### ISSUE TITLE
Unable to Run Docker Container

### ISSUE THREAD

**Issue by BrianMay-AO** [dataunitylab/jsonoid-discovery#2]
I pulled down the `michaelmior/jsonoid-discovery:latest` image today and it is not working as expected. I am aware that this might be because I'm trying to run it on a Macbook with an M2 chip. I have been able to run other amd64 images.

Image ID: `a4f4c6137331`
Digest: `sha256:f911fda8d977eccdb64e206126e01fc1060539b23b8181b396fe6f707a6fec22`
Created: 6 days ago (as of March 13, 2024)

When I run the docker container as described in the README, it hangs forever. Even just running the `--help` hangs forever.
I'm running a command like: `docker run --rm -i --platform linux/amd64 michaelmior/jsonoid-discovery -h`

If I use the Docker terminal to modify the `/opt/docker/bin/discovery-schema` file and update the first line of the usage function like:
```diff
usage() {
-   cat <<EOM
+   cat <<'EOM' 
```
Then I am able to run `./bin/discovery-schema -h` and see the usage output from within the docker container's terminal.

Notably, if I edit that same file and add an echo command immediately after the "Main script" comment, I do not ever see the log and it continues to hang forever.

**Comment by BrianMay-AO** [comment]
I got it working! It looks like some Docker update turned off the Rosetta setting unexpectedly.

Thanks for a very cool tool!

**Comment by michaelmior** [comment]
Whoops. Sorry I missed this issue earlier. Glad this is working for you!
